# @package _global_
model:
  
  # Adapter configuration
  adapter:
    path: "eo_core.adapters.bigearthnet_adapter"
    class: "BigEarthNetAdapter"
    params:
      model_config:
        pretrained_model_name_or_path: "BIFOLD-BigEarthNetv2-0/convnextv2_base-s2-v0.2.0"
      
      bands: ['B02', 'B03', 'B04', 'B05', 'B06', 'B07', 'B08', 'B8A', 'B11', 'B12']
      
      # Normalization stats for 0-1 Reflectance Range (10-band version)
      means: [0.0429, 0.0614, 0.0590, 0.0950, 0.1792, 0.2075, 0.2218, 0.2266, 0.1594, 0.1009]
      stds: [0.0572, 0.0582, 0.0675, 0.0729, 0.1096, 0.1273, 0.1365, 0.1356, 0.0836, 0.0818]
      
      patch_size: 120
      stride: 60
      batch_size: "auto"
pipeline:
  output:
    save_gradient_preview: true